var arrLang = {
      "en" : {
      "Home": "Home",
      "Features": "Features",
      "Links": "Links",
      "Markets": "Markets",
      "Explorer": "Explorer",
      "Download": "Download",
      "Force Network": "Force Network",
      "The Internet. Redefined": "The Internet. Redefined.",
      "Text1": "The Force Network is a new set of protocols for an internet where everything can be private, everyone can be anonymous, and nothing can be censored.",
      "Text2": "Introducing the world's first Decentralized Scalable Network (DSNS) Solution",
      "The Force Network": "The Force Network",
      "Text3": "A cryptocurrency solution that enables real network privacy. Incentivised nodes facilitate the transfer of encrypted information that keeps the source and destination IP addresses hidden from each other.",
      "Text4": "No longer to you need to trust intermediaries to route data without spying on, blocking, modifying or selling it along the way.",
      "Text5": "With Force Network, no one can tell who the sender or the receiver is and no one can read the data while it is in transit.",
      "Text6": "No longer will apps reveal your sensitive information to host.",
      "Text7": "With Force Network, connections utilize trustless end-to-end encryption, routing and substitution protocols that restricts access to your informations.",
      "Text8": "No longer give your internet service provider access to your network traffic and website metadata.",
      "Text9": "Force Network enables net neutrality by providing a customizable, encrypted, and multi-layered network path that keeps your informations private.",
      "SECURE & PRIVATE": "SECURE & PRIVATE",
      "Network Features": "Network Features",
      "Low Latency": "Low Latency",
      "Text10": "Hop node routing chains can be custom-built to create fast, low-latency network paths using approximate node location data. For ultimate anonymity, location-aware routing is optional.",
      "Censorship Resistance": "Censorship Resistance",
      "Text11": "With Force, the users and hosts IP/metadata are completely hidden from each other. This keeps the hosts safe from discovery, the data safe from censorship, and the users anonymous.",
      "Expandable Protocols": "Expandable Protocols",
      "Text12": "The Force network supports community-developed routing protocols that enable payload data to be wrapped in an infinite number of ways. These protocols build on top of the flexible routing architecture to provide additional network capabilities and keep traffic indistinguishable from other types of internet usage.",
      "REVENUE GENERATION": "REVENUE GENERATION",
      "Platform Features": "Platform Features",
      "Smart Incentives": "Smart Incentives",
      "Scalable Services": "Scalable Services",
      "Automated Pricing": "Automated Pricing",
      "Text13": "Utilizing Blockchain technology the Network incentivizes those with network resources to share them with others in exchange for FOR tokens. Service packages are built by “payment nodes” that can be managed from the in-wallet browser to make using the Network simple for end-users. Services can also be contracted directly for advanced users.",
      "Text14": "Nodes can provide any number of network services based on which protocols they want to support and their resources available. We anticipate the network could grow to support all modern communication protocols such as E-mail, streaming, torrents, gaming, messaging, etc.",
      "Text15": "Network prices are automatically adjusted in order to incentivize node operators to provide the most in-demand services while keeping prices comparable across different node providers. Automated pricing also keeps malicious nodes from underpricing others in order to damage the network.",
      "UPCOMING": "UPCOMING",
      "Roadmap": "Roadmap",
      "DISCOVER": "DISCOVER",
      "Media Links": "Media Links",
      "MARKETS": "MARKETS",
      "Where to buy FOR": "Where to buy FOR",
      "WALLET": "WALLET",
      "Available for all major desktop platforms": "Available for all major desktop platforms",
      "Contact us": "Contact us",
      "Copyright": "COPYRIGHT © 2018. ALL RIGHTS RESERVED. FORCENETWORK."
  },
  "ru" : {
        "Home": "Начало",
        "Features": "Особенности",
        "Links": "Ссылки",
        "Markets": "Рынки",
        "Explorer": "Исследователь",
        "Download": "Скачать",
        "Force Network": "Force Network",
        "The Internet. Redefined": "Интернет. Пересмотрен.",
        "Text1": "Force Network - это новый набор протоколов для интернета, где все может быть конфиденциальным, каждый может быть анонимен, и ничто не может быть подвергнуто цензуре.",
        "Text2": "Предоставляем первое в мире Решение Децентрализованной Масштабируемой Сети (DSNS)",
        "The Force Network": "Force Network",
        "Text3": "Решение основанное на технологии блокчейн, которое обеспечивает реальную конфиденциальность сети. Стимулируемые (Ноды) узлы облегчают передачу зашифрованной информации, которая скрывает друг от друга источник и назначение IP-адресов.",
        "Text4": "Больше нет необходимости доверять посредникам, чтобы с их помощью маршрутизировать данные, при этом не следя, не блокируя или не изменяя или продавая свои данные в течении этого пути.",
        "Text5": "Благодаря Force, никто не сможет определить, кто отправитель и кто получатель, и никто не сможет прочитать данные, пока они находятся в пути.",
        "Text6": "Приложения больше не будут раскрывать в хостах Вашу конфиденциальную информацию.",
        "Text7": "Благодаря Force Network, соединения используют надежные, комплексные протоколы шифрования, маршрутизацию и подменные протоколы, которые ограничивают доступ к Вашей информации.",
        "Text8": "Больше нет необходимости предоставлять Вашему интернет-провайдеру доступ к Вашему сетевому трафику и метаданным сайта.",
        "Text9": "Force обеспечивает сетевой нейтралитет, предоставляя настраиваемый, зашифрованный и многоуровневый сетевой путь, благодаря чему, Ваша информация остается всегда конфиденциальной.",
        "SECURE & PRIVATE": "Безопасный И Конфиденциальный",
        "Network Features": "Функции Сети",
        "Low Latency": "Низкое Время Ожидания",
        "Text10": "Узлы маршрутизации (hop node) могут произвольно настраиваться для создания быстрых сетевых путей с низким временем ожидания, используя приблизительные данные о местоположении узла. Для окончательной анонимности местоположение маршрутизации по желанию.",
        "Censorship Resistance": "Устойчивость к цензуре",
        "Text11": "С помощью Force, IP / метаданные протоколы они хотят поддерживать и на основе каких протоколов их ресурсы доступны. Мы ожидаем, что сеть может расти для поддержки всех современных протоколов передачи данных, таких как: электронная почта, стриминг, торренты, игры, обмен сообщениями и т. д.",
        "Expandable Protocols": "Расширяемые Протоколы",
        "Text12": "Force Network поддерживает разработанные сообществом протоколы маршрутизации, которые позволяют полезным датам быть \"завернутым\" бесконечным числом способов. Эти протоколы строятся поверх гибкой архитектуры маршрутизации, чтобы обеспечить дополнительные сетевые возможности и чтобы сделать трафик неотличимым от других видов использования интернета.",
        "REVENUE GENERATION": "Генерация Доходов",
        "Platform Features": "Функции Платформы",
        "Smart Incentives": "Умное стимулирование",
        "Scalable Services": "Масштабируемые Услуги",
        "Automated Pricing": "Автоматизированное Ценообразование",
        "Text13": "Используя технологию Блокчейн, сеть стимулирует операторов сети и поставщиков использовать внутренний токен FOR. Услуги спроектированы с помощью специальных платежных узлов, управляемых в браузере кошелька, которые упрощают использование сети для конечных пользователей и могут легко управляться из браузера в кошельке.",
        "Text14": "Узлы могут предоставлять любое количество сетевых сервисов решая, на основе каких протоколов они хотят это поддерживать и на основе каких протоколов их ресурсы доступны. Мы ожидаем, что сеть может расти для поддержки всех современных коммуникационных протоколов, таких как: электронная почта, стриминг, торренты, игры, обмен сообщениями и т. д.",
        "Text15": "Цены на сеть автоматически корректируются, чтобы стимулировать операторов узлов предоставлять наиболее востребованные услуги, при этом сохраняя цены сопоставимыми с ценами других поставщиков узлов. Автоматическое ценообразование также предотвращает от занижения цен вредоносными узлами, в целях повреждения сети.",
        "UPCOMING": "Предстоящие события",
        "Roadmap": "Дорожная Карта",
        "DISCOVER": "Узнай Больше",
        "Media Links": "Ссылки СМИ",
        "MARKETS": "Биржи",
        "Where to buy FOR": "Где купить FOR",
        "WALLET": "Кошелек",
        "Available for all major desktop platforms": "Доступно для всех основных настольных платформ",
        "Contact us": "Свяжитесь с нами",
        "Copyright": "© . 2018. Все права защищены. FORCENETWORK."
  },

  "fr" : {

  "Home": "Accueil",
      "Features": "Fonctionnalités",
      "Links": "Liens",
      "Markets": "Exchanges",
      "Explorer": "Explorer",
      "Download": "Télécharger",
      "Force Network": "Force Network",
      "The Internet. Redefined": "Internet. Redéfini.",
      "Text1": "Force Network est un nouvel ensemble de protocoles pour un Internet où tout peut être privé, tout le monde peut être anonyme, et rien ne peut être censuré.",
      "Text2": "Présentation de la première solution de réseau flexible décentralisé (DSNS) au monde",
      "The Force Network": "Force Network",
      "Text3": "Une solution de crypto-monnaie qui permet une véritable confidentialité du réseau. Les nœuds incitatifs facilitent le transfert des informations chiffrées qui gardent les adresses IP source et de destination cachées les unes des autres.",
      "Text4": "Vous n'avez plus besoin de faire confiance aux intermédiaires pour acheminer vos données sans les espionner, les bloquer, les modifier ou les vendre en cours de route.",
      "Text5": "Avec Force Network, personne ne peut dire qui est l'expéditeur ou le destinataire et personne ne peut lire les données pendant son transit.",
      "Text6": "Les applications ne dévoileront plus vos informations sensibles à l’hôte.",
      "Text7": "Avec Force Network, les connexions utilisent des protocoles de chiffrement, de routage et de substitution de bout en bout, qui limitent l'accès à vos informations.",
      "Text8": "Ne donnez plus accès à votre fournisseur d'accès Internet à votre trafic réseau et aux métadonnées de vos sites Internet.",
      "Text9": "Force Network permet la neutralité du réseau en fournissant un chemin réseau personnalisable, crypté et multi-couches qui garde vos informations confidentielles.",
      "SECURE & PRIVATE": "SECURISÉ & PRIVÉ",
      "Network Features": "Fonctionnalités du réseau",
      "Low Latency": "Faible latence",
"Text10": "Les chaînes de routage des Hop nodes peuvent être personnalisées pour créer des chemins de réseau rapides et à faible latence à l'aide de données d'emplacement de nœud approximatives. Pour un anonymat ultime, le routage prenant en compte l'emplacement est facultatif.",
      "Censorship Resistance": "Résistance à la censure",
      "Text11": "Avec Force, les utilisateurs et les hôtes IP / métadonnées sont complètement cachés les uns des autres. Cela protège les hôtes contre la découverte, les données contre la censure et les utilisateurs anonymes."
"Expandable Protocols": "Protocoles extensibles",
      "Text12": "Le réseau Force prend en charge les protocoles de routage développés par la communauté, qui permettent d’encapsuler les données utiles dans un nombre infini de façons. Ces protocoles s’appuient sur l’architecture de routage flexible pour fournir des capacités de réseau supplémentaires et permettre de distinguer le trafic des autres types d’utilisation d’Internet.",
      "REVENUE GENERATION": "GÉNÉRATION DE REVENUS",
      "Platform Features": "Caractéristiques de la plate-forme",
      "Smart Incentives": "Incitations intelligentes",
      "Scalable Services": "Services flexibles",
      "Automated Pricing": "Tarification automatisée",
      "Text13": "Grâce à la technologie Blockchain, le réseau encourage les personnes disposant de ressources réseau à les partager avec d’autres en échange de jetons FOR. Les packages de services sont construits par des «nœuds de paiement» qui peuvent être gérés à partir du navigateur intégré au portefeuille pour simplifier l’utilisation du réseau pour les utilisateurs finaux. Les services peuvent également être contractés directement pour les utilisateurs avancés.",
"Text14": "Les nœuds peuvent fournir un nombre illimité de services réseau en fonction des protocoles qu'ils souhaitent prendre en charge et de leurs ressources disponibles. Nous prévoyons que le réseau pourrait croître pour prendre en charge tous les protocoles de communication modernes tels que le courrier électronique, le streaming, les torrents, les jeux, la messagerie, etc.",
"Text15": "Les prix du réseau sont automatiquement ajustés afin d'inciter les opérateurs de nœuds à fournir les services les plus demandés tout en maintenant des prix comparables entre les différents fournisseurs de nœuds. La tarification automatisée empêche également les nœuds malveillants de sous-évaluer les autres afin d'endommager le réseau.",
      "UPCOMING": "À VENIR",
      "Roadmap": "Roadmap",
      "DISCOVER": "DÉCOUVRIR",
      "Media Links": "Liens média",
      "MARKETS": "EXCHANGES",
      "Where to buy FOR": "Où acheter du FOR",
      "WALLET": "PORTEFEUILLE",
      "Available for all major desktop platforms": "Disponible dans la majorité des systèmes d'exploitation",
      "Contact us": "Contactez-nous",
      "Copyright": "COPYRIGHT © 2018. TOUS DROITS RÉSERVÉS. FORCENETWORK."
}

};

$(function(){
  $('.translate').click(function(){
    var lang = $(this).attr('id');

    $('.lang').each(function(index, element){
      $(this).text(arrLang[lang][$(this).attr('key')]);
    });
  });
});
